---
kind: Service
apiVersion: v1
metadata:
  name: hello-joker
spec:
  selector:
    app: hello-joker
  ports:
    - port: 8080
      name: http
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: hello-joker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-joker
    spec:
      containers:
      - name: hello-joker
        image: localhost:5000/hello-joker:2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /hello-joker/resources/hello
            port: 8080
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: hello-joker
spec:
  rules:
    - host: kubernetes.local
      http:
        paths:
        - path: /hello-joker
          backend:
            serviceName: hello-joker
            servicePort: 8080
---